### ISSUE TITLE
need to create the build dir

### ISSUE THREAD

**Issue by zhangsen** [Vassius/xmUtil#1]
Hi,

Thanks for the tool. Not sure about other systems, but here (fedora) the build dir has to be created beforehand, or else,

$ make
gcc -g -c src/xmutil.c -o build/xmutil.o -Wall -Werror
Assembler messages:
Fatal error: can't create build/xmutil.o: No such file or directory
make: **\* [build/xmutil.o] Error 1

Fix should be trivial..

**Comment by Vassius** [comment]
Fixed in 7af456692061cb3246e9bbc47c59314b178721fe

Sorry about the delay. :P
